### ISSUE TITLE
Act 6 #2

### ISSUE THREAD

**Issue by hcientist** [StoneyJackson/CollabDev#14]
Should [Question 2](https://github.com/StoneyJackson/CollabDev/blame/master/Activities/Act06_Git_Branching/Activity.md#L48) actually read: "changes the working copy" rather than "changes the current commit"?

**Comment by StoneyJackson** [comment]
Yes. That's more clear and accurate. Thanks!

https://github.com/StoneyJackson/CollabDev/commit/7c2247629b810238890f6a874a35f63a6e049a74
